function planetColorButton(universe)

    fig = uifigure('Name', 'Customize your planet');
    colorButton = uibutton(fig, 'push',...
        'Text', 'Color', ...
        'Position', [325, 200, 200, 22],...
        'ButtonPushedFcn', @(colorButton, event) changePlanetColor(universe));

    startButton = uibutton(fig, 'push', ...
        'Text', 'START', ...
        'Position', [75, 200, 200, 22], ...
        'ButtonPushedFcn', @(startButton, event) startUniverse(universe));
    
    radiusIncrease = uibutton(fig, 'push', ...
        'Text', '+', ...
        'Position', [350, 100, 100, 22], ...
        'ButtonPushedFcn', @(radiusInrease, event) increasePlanetRadius(universe));

    radiusDecrease = uibutton(fig, 'push', ...
        'Text', '-', ...
        'Position', [150, 100, 100, 22], ...
        'ButtonPushedFcn', @(radiusInrease, event) decreasePlanetRadius(universe));
 
end