function startPage(universe)

    colorButtonWidth = 25;
    colorButtonHeight = 25;
    colorButtonLeft = 200;
    colorButtonBottom = 300;

    fig = uifigure('Name', 'Customize your planet');
    p = uipanel('Parent', fig, 'Title','Planet Color',...
             'Position',[210 295 155 55]);

    planetColors = {'r', 'g', 'b', 'c', 'm'};
    
    c = 1;
    while c <= 5
        uibutton(fig, 'push',...
            'Text', '', ...
            'BackgroundColor', planetColors{c}, ...
            'Position', [colorButtonLeft + c * colorButtonWidth, colorButtonBottom, colorButtonWidth, colorButtonHeight], ...
            'ButtonPushedFcn', @(colorButton, event) changePlanetColor(universe, planetColors{c}));
        c = c + 1;
    end

    startButton = uibutton(fig, 'push', ...
        'Text', 'START', ...
        'Position', [185, 100, 200, 22], ...
        'ButtonPushedFcn', @(startButton, event) startUniverse(universe));
    
    radiusIncrease = uibutton(fig, 'push', ...
        'Text', '+', ...
        'Position', [335, 175, 100, 22], ...
        'ButtonPushedFcn', @(radiusInrease, event) increasePlanetRadius(universe));

    radiusDecrease = uibutton(fig, 'push', ...
        'Text', '-', ...
        'Position', [135, 175, 100, 22], ...
        'ButtonPushedFcn', @(radiusDecrease, event) decreasePlanetRadius(universe));

    distanceIncrease = uibutton(fig, 'push', ...
        'Text', 'D: +', ...
        'Position', [335, 250, 100, 22], ...
        'ButtonPushedFcn', @(distanceIncrease, event) increaseDistance(universe));

    distanceDecrease = uibutton(fig, 'push', ...
        'Text', 'D: -', ...
        'Position', [135, 250, 100, 22], ...
        'ButtonPushedFcn', @(distanceDecrease, event) decreaseDistance(universe));
 
end